ALTER TABLE public.app_settings
ADD COLUMN IF NOT EXISTS barcode_width TEXT DEFAULT '50mm',
ADD COLUMN IF NOT EXISTS barcode_height TEXT DEFAULT '30mm',
ADD COLUMN IF NOT EXISTS barcode_font_size TEXT DEFAULT '12px',
ADD COLUMN IF NOT EXISTS license_status BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS license_expiry TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS enable_notifications BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS enable_sounds BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS task_reminders BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS sales_notifications BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS low_stock_notifications BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS low_stock_alert BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS low_stock_threshold INTEGER DEFAULT 10,
ADD COLUMN IF NOT EXISTS prevent_zero_stock_sales BOOLEAN DEFAULT false;
