CREATE TABLE IF NOT EXISTS public.app_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  company_name TEXT,
  currency TEXT,
  tax_rate REAL,
  invoice_header TEXT,
  invoice_footer TEXT,
  theme TEXT,
  accent_color TEXT,
  logo TEXT,
  date_format TEXT,
  direct_print BOOLEAN DEFAULT false,
  paper_width TEXT,
  receipt_font_size TEXT,
  phone TEXT,
  address TEXT,
  show_details BOOLEAN DEFAULT true,
  barcode_direct_print BOOLEAN DEFAULT false,
  barcode_width TEXT,
  barcode_height TEXT,
  barcode_font_size TEXT,
  maintenance_note TEXT,
  warranty_terms TEXT,
  maintenance_footer TEXT,
  app_font_size INTEGER DEFAULT 100,
  whatsapp_maintenance_template TEXT,
  invoice_numbering JSONB,
  transfer_settings JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id)
);

-- Enable RLS
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view their own app_settings"
  ON public.app_settings FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own app_settings"
  ON public.app_settings FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own app_settings"
  ON public.app_settings FOR UPDATE
  USING (auth.uid() = user_id);
